services:
  - type: web
    name: laravel-portfolio
    env: docker
    plan: free
    branch: main
    repo: https://github.com/marklouie-abayhon/mark-portfolio
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
